INVERT_Y_AXIS = True;

A_BUTTON = 0;
B_BUTTON = 1;
X_BUTTON = 2;
Y_BUTTON = 3;

LEFT_BUMPER_BUTTON = 4;
RIGHT_BUMPER_BUTTON = 5;
LEFT_STICK_BUTTON = 9;
RIGHT_STICK_BUTTON = 10;

LEFT_TRIGGER_AXIS = 2;
RIGHT_TRIGGER_AXIS = 5;
LEFT_STICK_X_AXIS = 0;
LEFT_STICK_Y_AXIS = 1;
RIGHT_STICK_X_AXIS = 3;
RIGHT_STICK_Y_AXIS = 4;
